// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAch7mwjenboG97VLHcxnzKQ08H40Mn2Hc',
    appId: '1:588133653218:android:cc23a5fe32672934935cbb',
    messagingSenderId: '588133653218',
    projectId: 'todo-new-app-ad2da',
    storageBucket: 'todo-new-app-ad2da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDae8XB4oMWFINDFC3yq2Y4Uz4tQiND-S0',
    appId: '1:588133653218:ios:fb8ef139f9a2b4d2935cbb',
    messagingSenderId: '588133653218',
    projectId: 'todo-new-app-ad2da',
    storageBucket: 'todo-new-app-ad2da.appspot.com',
    iosClientId: '588133653218-lletkilk7n0gosvsh9iicaai6a24ta0u.apps.googleusercontent.com',
    iosBundleId: 'com.app.todoNewApp',
  );
}
